### ISSUE TITLE
The arm can't move

### ISSUE THREAD

**Issue by aubiao** [lihuang3/ur5_notebook#26]

**Comment by aubiao** [comment]
the terminal print warn when the red box cross the camera
--------------------------------------------------------------------------
[ WARN] [1595472688.063235819, 117.205000000]: The complete state of the robot is not yet known.  Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
[ WARN] [1595472695.682415864, 118.245000000]: The complete state of the robot is not yet known.  Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
[ WARN] [1595472703.519119242, 119.245000000]: The complete state of the robot is not yet known.  Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
-----------------------------------------------------

also, some error
--------------------------------------------------------
[ERROR] [1595471981.780210349, 0.130000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/shoulder_pan_joint
[ERROR] [1595471981.784470315, 0.130000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/shoulder_lift_joint
[ERROR] [1595471981.788446378, 0.130000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/elbow_joint
[ERROR] [1595471981.794961431, 0.130000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/wrist_1_joint
--------------------------------------------------------------
I can't solve the problem,please help me,thanks.

**Comment by aubiao** [comment]
![2020-07-23 11-09-37屏幕截图](https://user-images.githubusercontent.com/17949349/88248904-51298f80-ccd5-11ea-828b-811988bac320.png)

**Comment by learningxiaobai** [comment]
> ## the terminal print warn when the red box cross the camera
> ## [ WARN] [1595472688.063235819, 117.205000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
> [ WARN] [1595472695.682415864, 118.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
> [ WARN] [1595472703.519119242, 119.245000000]: The complete state of the robot is not yet known. Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8
> ## also, some error
> ## [ERROR] [1595471981.780210349, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_pan_joint
> [ERROR] [1595471981.784470315, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/shoulder_lift_joint
> [ERROR] [1595471981.788446378, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/elbow_joint
> [ERROR] [1595471981.794961431, 0.130000000]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/wrist_1_joint
> I can't solve the problem,please help me,thanks.

have you solved？i have same questions

**Comment by zcz-vvv** [comment]
@learningxiaobai  i have same questions,have you solved?please help me,thank you

**Comment by zcz-vvv** [comment]
@aubiao  i have same questions,have you solved?please help me,thank you

**Comment by learningxiaobai** [comment]
> @learningxiaobai i have same questions,have you solved?please help me,thank you

sorry，i have't ,have you solved?

**Comment by Jayce-Jayce** [comment]
have you guys solved? i met the same thing.

**Comment by weakenleg** [comment]
have you solved? i met the same thing.

**Comment by hxn8439** [comment]
I have the same problem too. The robot arm suppose to move after executing
roslaunch ur5_notebook initialize.launch

So, I also execute python testvisionplanner.py and testmove2.py but endup with this error return.

[ERROR] [1630771695.765029]: Unable to immediately register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.

so the error is happening at the master node communication.

**Comment by onehuan** [comment]
have you guys solved? i met the same thing.

**Comment by onehuan** [comment]
> 

have you guys solved? i met the same thing.

**Comment by onehuan** [comment]
> I have the same problem too. The robot arm suppose to move after executing roslaunch ur5_notebook initialize.launch
> 
> So, I also execute python testvisionplanner.py and testmove2.py but endup with this error return.
> 
> [ERROR] [1630771695.765029]: Unable to immediately register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
> 
> so the error is happening at the master node communication.

have you guys solved? i met the same thing.

**Comment by onehuan** [comment]
> have you solved? i met the same thing.

have you guys solved? i met the same thing.

**Comment by hxn8439** [comment]
Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work.

**Comment by onehuan** [comment]
Thank you very much, and I will try it agian.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hamilton ***@***.***&gt;; 
发送时间: 2021年12月26日(星期天) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lihuang3/ur5_ROS-Gazebo] The arm can&#39;t move (#26)





 
Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hwan30** [comment]
Is using melodic the only fix to this issue?
I have used both kinetic and noetic and same issue persists.

**Comment by Motion77** [comment]
> have you guys solved? i met the same thing.
have you guys solved? i met the same thing.

**Comment by Motion77** [comment]
> have you guys solved? i met the same thing.

Have you guys solved? I met the same thing.

**Comment by Motion77** [comment]
> Thank you very much, and I will try it agian.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hamilton ***@***.***&gt;; 发送时间: 2021年12月26日(星期天) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lihuang3/ur5_ROS-Gazebo] The arm can&#39;t move (#26) Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

Have you guys solved? I met the same thing.

**Comment by JinchuanMa** [comment]
> Thank you very much, and I will try it agian.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hamilton ***@***.***&gt;; 发送时间: 2021年12月26日(星期天) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lihuang3/ur5_ROS-Gazebo] The arm can&#39;t move (#26) Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

Have you guys solved? I met the same thing.

**Comment by onehuan** [comment]
> > Thank you very much, and I will try it agian.
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Hamilton _**@**_._**>; 发送时间: 2021年12月26日(星期天) 中午1:34 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [lihuang3/ur5_ROS-Gazebo] The arm can't move (#26) Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> Have you guys solved? I met the same thing.

sorry, i didn't solve the problem

**Comment by JinchuanMa** [comment]
> Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work.

Hello, when I run the melodic version, the red object cannot move, have you encountered it?

**Comment by JinchuanMa** [comment]
> Is using melodic the only fix to this issue? I have used both kinetic and noetic and same issue persists.

have you guys solved? i met the same thing.

**Comment by JinchuanMa** [comment]
> Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work.
Hello, using the melodic version, is there anything to modify?

**Comment by JinchuanMa** [comment]
> Yes, it is resolved, it turns out that I have to converted to melodic distribution. You can find the repository with a melodic distribution at https://github.com/hxn8439/ur5_ROS-Gazebo-Melodic. I listed a github user, lihuang3, as the main contributor of the work.
can you give me your contact information？

**Comment by 2000222** [comment]
I run the melodic version code with ros noetic, but the robot can not move either, even with the following issues: 

[ERROR] [1661952199.436096, 3.621000]: bad callback: <bound method ur5_mp.tracking_callback of <__main__.ur5_mp object at 0x7f1a6be80ee0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/sarah/ur5_ws/src/ur5_ROS-Gazebo-Melodic/ur5_mp.py", line 167, in tracking_callback
    if len(self.pointx)>9:
AttributeError: 'ur5_mp' object has no attribute 'pointx'
